server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: JPA-Dameng-Demo
  jpa:
    open-in-view: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  datasource:
    dm:
      url: jdbc:dm://localhost:5236/test
      jdbcUrl: jdbc:dm://localhost:5236/test
      username: SYSDBA
      password: ChinaGexu4398.
      driver-class-name: dm.jdbc.driver.DmDriver
      dialect: org.hibernate.dialect.DmDialect
      hikari:
        maximum-pool-size: 100
        minimum-idle: 30